# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b6cd144f490110c61912cabee98b8048896600158b1a284289a5755c7b5dd28b6074ba3eb23e28d577b6e9bbb2ae5d8e476006f6f4b5809d8e7fb25a1a9f5c0

test:
  secret_key_base: bc15081ea88f7cbed479eeffd6bc0e0a4127d1d1436b1ac8e5d62974628334af9d2e3ab4071c03ee6e955e29cf3d440220db3091eb1d29b018746fd959b07ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
